[package]
name = "backend"
version = "0.1.0"
authors = ["Scott Checko <schecko@sfu.ca>"]
publish = false

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
actix-web = "1.0.0"
actix-files = "0.1.1"
rppal = "0.11.2"
serialport = "3.2.0"
server = { path = ".." }
web = { path = "../web" }

[build-dependencies]
server = { path = ".." }
