[package]
name = "backend"
version = "0.1.0"
authors = ["Scott Checko <schecko@sfu.ca>"]
publish = false

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
rppal = "0.11.2"
serialport = "3.2.0"
server = { path = ".." }

[build-dependencies]
server = { path = ".." }
