[package]
authors = ["Scott Checko <schecko@sfu.ca>"]
edition = "2018"
name = "backend"
publish = false
version = "0.1.0"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
actix-files = "0.1.1"
actix-web = "1.0.0"
common = { path = "../common" }
rppal = "0.11.2"
serialport = "3.2.0"

[build-dependencies]
common = { path = "../common" }
