[package]
authors = ["Scott Checko <schecko@sfu.ca>"]
edition = "2018"
name = "backend"
publish = false
version = "0.1.0"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
actix = "0.8.2"
actix-files = "0.1.1"
actix-session = "0.1.0"
actix-web = "1.0.0"
common = { path = "../common" }
env_logger = "0.6.1"
rppal = "0.11.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serialport = "3.2.0"

[build-dependencies]
common = { path = "../common" }
