[package]
authors = ["Scott Checko <schecko@sfu.ca>"]
edition = "2018"
name = "frontend"
publish = false
version = "0.1.0"

[dependencies]
common = { path = "../common" }
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
yew = "0.6.0"

[build-dependencies]
common = { path = "../common" }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
