[package]
name = "web"
version = "0.1.0"
authors = ["Scott Checko <schecko@sfu.ca>"]
publish = false

[lib]
name = "web"
path = "web.rs"

[[bin]]
name = "web"
path = "web.rs"

[dependencies]
actix-web = "1.0.0"
