[package]
name = "backend"
version = "0.1.0"
authors = ["Scott Checko <schecko@sfu.ca>"]
publish = false

[lib]
name = "backend"
path = "backend.rs"

[[bin]]
name = "backend"
path = "backend.rs"

[dependencies]
rppal = "0.11.2"
serialport = "3.2.0"
